seed_everything: 42
trainer:
  callbacks:
    class_path: Metric
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: "results"
  accelerator: "auto"
  auto_select_gpus: true
  devices: 1
