seed_everything: 42
trainer:
  callbacks:
    - class_path: src.callbacks.metric.Metric
    - class_path: pytorch_lightning.callbacks.RichModelSummary
      init_args:
        max_depth: 1
    - class_path: pytorch_lightning.callbacks.RichProgressBar
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: ???
        mode: auto
        verbose: True
        patience: 3
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: ???
        mode: auto
        verbose: True
        save_last: True
        save_top_k: 1
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: "results"
  accelerator: "auto"
  auto_select_gpus: true
  devices: 1
