seed_everything: 42
trainer:
  callbacks:
    - class_path: src.callbacks.metric.Metric
    - class_path: pytorch_lightning.callbacks.RichModelSummary
      init_args:
        max_depth: 1
    - class_path: pytorch_lightning.callbacks.RichProgressBar
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: "results"
  accelerator: "auto"
  auto_select_gpus: true
  devices: 1
