name: mrpc
seed_everything: 123
trainer:
  max_epochs: 30
model:
  class_path: GLUETransformer
  init_args:
    model_name_or_path: bert-base-uncased
    max_length: 256
data:
  class_path: GLUEDataModule
  init_args:
    task_name: mrpc
    batch_size: 32
    num_workers: 0
    pin_memory: true
